# Generated by Django 5.2.6 on 2025-09-07 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('short', 'Short'), ('gloves', 'Gloves'), ('boots', 'Boots'), ('ball', 'Ball'), ('socks', 'Socks'), ('others', 'Others')], max_length=10)),
                ('brand', models.CharField(choices=[('adios', 'Adios'), ('Niki', 'Niki'), ('miles', 'Miles'), ('umbre', 'Umbre'), ('erspa', 'Erspa'), ('amersfoort', 'Amersfoort'), ('seabook', 'Seabook')], max_length=10)),
                ('numeric_size', models.IntegerField()),
                ('alphabetic_size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
